services:
  - type: web
    name: smart-campus-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PIP_NO_CACHE_DIR
        value: "1"
